apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs-vol-class-gp2
status:
  accessModes:
  - ReadWriteOnce

