apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: default
spec:
  ports:
  - name: nexus-port
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: docker-port
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: nexus
  sessionAffinity: None
  type: ClusterIP

