apiVersion: v1
kind: Service
metadata:
  name: gitlab-k8s
  namespace: monitoring
  labels:
    k8s-app: gitlab
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: api
    port: 443
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gitlab-k8s
  namespace: monitoring
  labels:
    k8s-app: gitlab
subsets:
- addresses:
  - ip: 172.31.0.200
    nodeName: gitlab0
  ports:
  - name: api
    port: 443
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-k8s
  namespace: monitoring
  labels:
    k8s-app: gitlab-k8s
spec:
  jobLabel: k8s-app
  endpoints:
  - port: api
    interval: 30s
    scheme: https
    path: /-/metrics #use white list, not token #?token=csWQcmrw1g2xKS2Q3ggz
    #params:
    #  token: csWQcmrw1g2xKS2Q3ggz
    honorLabels: true
    tlsConfig:
      #use insecureSkipVerify only if you cannot use a Subject Alternative Name
      insecureSkipVerify: true
      #serverName: ETCD_DNS_OR_ALTERNAME_NAME
  selector:
    matchLabels:
      k8s-app: gitlab
  namespaceSelector:
    matchNames:
    - monitoring