apiVersion: v1
kind: Service
metadata:
  name: gitlab-monitor
  namespace: monitoring
  labels:
    k8s-app: gitlab
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: monitor
    port: 9168
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gitlab-monitor
  namespace: monitoring
  labels:
    k8s-app: gitlab
subsets:
- addresses:
  - ip: 172.31.0.200
    nodeName: gitlab0
  ports:
  - name: monitor
    port: 9168
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-monitor
  namespace: monitoring
  labels:
    k8s-app: gitlab-monitor
spec:
  jobLabel: k8s-app
  endpoints:
  - port: monitor
    interval: 30s
    scheme: http
    path: /process #use white list, not token #?token=csWQcmrw1g2xKS2Q3ggz
    honorLabels: true
  - port: monitor
    interval: 30s
    scheme: http
    path: /sidekiq
    honorLabels: true
    
  selector:
    matchLabels:
      k8s-app: gitlab
  namespaceSelector:
    matchNames:
    - monitoring