apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: ingress-nginx
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
---  
apiVersion: v1
kind: Service
metadata:
  name: ingress-metrics
  namespace: ingress-nginx
  labels:
    k8s-app: ingress
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 10254
    protocol: TCP
  selector:
    app: ingress-nginx
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-metrics
  namespace: monitoring
  labels:
    k8s-app: ingress-metrics
spec:
  jobLabel: k8s-app
  endpoints:
  - port: metrics
    interval: 30s
    scheme: http
    honorLabels: true
    
  namespaceSelector:
    matchNames:
    - ingress-nginx
  selector:
    matchLabels:
      k8s-app: ingress
