apiVersion: v1
kind: Service
metadata:
  name: jira-monitor
  namespace: monitoring
  labels:
    k8s-app: jira
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: monitor
    port: 9168
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jira-monitor
  namespace: monitoring
  labels:
    k8s-app: jira
subsets:
- addresses:
  - ip: 172.31.0.199
    nodeName: jira0
  ports:
  - name: monitor
    port: 443
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jira-monitor
  namespace: monitoring
  labels:
    k8s-app: jira-monitor
spec:
  jobLabel: k8s-app
  endpoints:
  - port: monitor
    interval: 30s
    scheme: https
    path: /plugins/servlet/prometheus/metrics
    tlsConfig:
      #use insecureSkipVerify only if you cannot use a Subject Alternative Name
      insecureSkipVerify: true
    honorLabels: true
  selector:
    matchLabels:
      k8s-app: jira
  namespaceSelector:
    matchNames:
    - monitoring