apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: default
spec:
  ports:
  - name: web-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jnlp-port
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins
  sessionAffinity: None
  type: ClusterIP

